### ISSUE TITLE
Payloads aren't serializable

### ISSUE THREAD

**Issue by Qix-** [jeanlauliac/kademlia-dht#1]
Kademlia payloads, in theory, should be fully serializable to keep the library fully network agnostic.

However, that doesn't seem to be the case - payloads use class objects which do not deserialize properly.

Is there any way for this to be fixed? I don't want to have to make payload-aware serialization, and right now there is absolutely no way to actually send this data over the wire in order to use this library properly.

**Comment by jeanlauliac** [comment]
Project is outdated/unmaintained.
